[package]
name = "pricedb"
version = "0.1.0"
authors = ["Alen Šiljak <dev@alensiljak.eu.org>"]
edition = "2021"
description = "Commodity price retrieval and storage. Helper for Plain-Text Accounting apps."
repository = "github.com/alensiljak/pricedb-rust"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0.26", features = ["derive"] }
confy = "0.5.1"
diesel = { version = "2.0.2", features = ["sqlite"] }
fast_log = "1.5.46"
log = "0.4.17"
#rbatis = "4.0.42"
#rbdc-sqlite = "0.1.14"
#rbs = "0.1.13"
serde = "1.0.147"
serde_derive = "1.0.147"
#sqlite = "0.30.1"
#libsqlite3-sys = { version = "*" }
#rusqlite = { version = "0.28.0", features = ["bundled"] }
#rusqlite = "0.28.0"
#sqlx = { version = "0.6.2", features = ["sqlite", "runtime-tokio-rustls"] }
#tracing = "0.1.37"
#tracing-subscriber = "0.3.16"
