[package]
name = "pricedb"
version = "1.3.1"
authors = ["Alen Šiljak <dev@alensiljak.eu.org>"]
edition = "2021"
description = "Commodity price retrieval, storage, and export in format compatible with Plain-Text Accounting applications."
repository = "https://github.com/alensiljak/pricedb-rust"
license = "GPL-3.0-or-later"
keywords = ["ledger", "ledger-cli", "finance", "cli"]
categories = ["command-line-utilities"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.66"
async-trait = "0.1.59"
chrono = "0.4.23"
clap = { version = "4.0.29", features = ["cargo", "derive"] }
confy = "0.5.1"
# diesel = { version = "2.0.2", features = ["sqlite"] }
env_logger = "0.10.0"
indicatif = "0.17.2"
log = "0.4.17"
once_cell = "1.16.0"
reqwest = { version = "0.11.13", features = ["json"] }
rstest = "0.16.0"
rust_decimal = "1.27.0"
rust_decimal_macros = "1.27.0"
rusqlite = { version = "0.28.0", features = ["bundled"] }
sea-query = { version = "0.27.2", features = ["attr", "backend-sqlite"] }
sea-query-rusqlite = "0.1.0"
serde = "1.0.149"
serde_derive = "1.0.149"
serde_json = "1.0.89"
# sqlx = { version = "0.6.2", features = ["sqlite", "runtime-tokio-rustls"] }
tempfile = "3.3.0"
test-log = "0.2.11"
#sqlite = "0.30.1"
tokio = { version = "1.23.0", features = ["full"] }

[dev-dependencies]
env_logger = "0.10.0"
