[package]
name = "pricedb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0.23", features = ["derive"] }
confy = "0.5.1"
serde = "1.0.147"
serde_derive = "1.0.147"
sqlite = "0.30.1"
#libsqlite3-sys = { version = "*" }
#rusqlite = { version = "0.28.0", features = ["bundled"] }
#rusqlite = "0.28.0"
#sqlx = { version = "0.6.2", features = ["sqlite", "runtime-tokio-rustls"] }
tracing = "0.1.37"
tracing-subscriber = "0.3.16"
