@startuml Components

database symbols
[app]
cloud internet
database prices

internet --> [app] : download prices
symbols -> [app] : load symbols
[app] -> [prices] : save prices
prices -> [app] : load existing

@enduml
